# Generated by Django 3.1.7 on 2021-04-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_carousel_carousel_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_css',
            field=models.CharField(default='active', max_length=200, null=True, verbose_name='CSS'),
        ),
    ]
