# Generated by Django 3.1.7 on 2021-04-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='workers_photo',
            field=models.ImageField(upload_to='workersimg'),
        ),
    ]
