# Generated by Django 3.1.7 on 2021-04-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20210409_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='workers_position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
