# Generated by Django 3.1.7 on 2021-04-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_text',
            field=models.TextField(default='Текст'),
        ),
    ]
