# Generated by Django 3.1.7 on 2021-04-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_news_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_photo',
            field=models.ImageField(default='-', upload_to='newsimg'),
        ),
    ]
