# Generated by Django 3.1.7 on 2021-04-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии галереи'},
        ),
    ]
